### ISSUE TITLE
Move dependencies to devDependencies

### ISSUE THREAD

**Issue by Kiyozz** [goosoftware/goo#2]
Hey, I'm the creator of electron-esbuild.

I'm warning that you should move your dependencies to devDependencies. Only external dependencies (not in the bundle) should be in `dependencies`. Why? Because used devDependencies are bundled in one js file.

Making them dependencies will bundled them in a js file and in the packaged node_modules folder

**Comment by johnrees** [comment]
Done, thanks for the warning @Kiyozz, and for your library :)
